import { User } from './user.model';
export interface Company{

      name: string,
      address: string,
      legalName: string,
      legalAddress: string,
      unit: string,
      street: string,
      city: string,
      province: string,
      postalCode: string,
      country: string,
      website: string,
      officeEmail: string,
      officePhone: string,
      billingEmail: string,
      billingPhone: string,
      billingAddress: string,
      billingUnit: string,
      billingStreet: string,
      billingCity: string,
      billingProvince: string,
      billingPostalCode: string,
      billingCountry: string,
      language: string,
      currency: string,
      timeZone: string,
      lengthUnit: string,
      temperatureScale: string,
      humidityScale: string,
      jobNumberFormat: string,
      xactimate: string,
      contact: string,
      numContact: string,
      phone: string,
      contract: string,
      finalDate: string,
      imagePath: string,
      status: string,
      userCreated: User,
      userEdit: User,
      _id?:string,
      __rowNum__?:string

}
